### ISSUE TITLE
"You are Following 0 users."

### ISSUE THREAD

**Issue by bfgelectronics** [htr-tech/unfollow-plus#2]
I tryed on multiple accounts, but the script always says "You are Following 0 users.".

**Comment by htr-tech** [comment]
@bfgelectronics blocked by instagram api 😢 try few more times

**Comment by bfgelectronics** [comment]
I tryed several times and still the same

**Comment by gecevicius** [comment]
I'm having the same issue, seems to not go away?

**Comment by htr-tech** [comment]
Account is in checkpoint .. 😢 first login in to your insta account & then Try 2/3 times more hopes that will work 😢 

Instagram api is blocking the login 😢
